<?php
$title = $this->title;
$plugins = $this->plugins;

$this->headTitle($title);

// Plugins
$pluginsForm = $this->pluginsForm;
$pluginsForm->prepare();

// Settings
$settingsForm = $this->settingsForm;
$settingsForm->prepare();

// Wallets
$walletsData = $this->walletsData;
?>

<h2 class="page-header"><?= $title ?></h2>

<!--Messages-->
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<!--Form plugins-->
<?= $this->form()->openTag($pluginsForm) ?>
<?= $this->formElement($pluginsForm->get('csrf')) ?>

<!--Plugins-->
<div id="pluginsPanel" class="panel panel-default">
    <div id="pluginsPanelHeading" class="panel-heading">
        <strong>Plugins</strong>
        <div class="pull-right">
            <?= $this->formElement($pluginsForm->get('submit')) ?>
        </div>
    </div>
    <div id="pluginsPanelBody" class="panel-body text-center">
        <div class="row">
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($pluginsForm->get('crypto')) ?>
                    <?= $this->formElement($pluginsForm->get('crypto')) ?>
                </div>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($pluginsForm->get('arlo')) ?>
                    <?= $this->formElement($pluginsForm->get('arlo')) ?>
                </div>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($pluginsForm->get('wemo')) ?>
                    <?= $this->formElement($pluginsForm->get('wemo')) ?>
                </div>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($pluginsForm->get('hue')) ?>
                    <?= $this->formElement($pluginsForm->get('hue')) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>

<!--Settings-->
<!--Form settings-->
<?= $this->form()->openTag($settingsForm) ?>
<?= $this->formElement($settingsForm->get('csrf')) ?>

<div id="settingsPanel" class="panel panel-default">
    <div id="settingsPanelHeading" class="panel-heading">
        <strong>Global</strong>
        <div class="pull-right">
            <?= $this->formElement($settingsForm->get('submit')) ?>
        </div>
    </div>
    <div id="settingsPanelBody" class="panel-body">
        <div class="row">
            <div class="col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($settingsForm->get('arlousername')) ?>
                    <?= $this->formElement($settingsForm->get('arlousername')) ?>
                </div>
            </div>
            <div class="col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($settingsForm->get('arlopassword')) ?>
                    <?= $this->formElement($settingsForm->get('arlopassword')) ?>
                </div>
            </div>
            <div class="col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($settingsForm->get('refresh')) ?>
                    <div class="input-group">
                        <?= $this->formElement($settingsForm->get('refresh')) ?>
                        <div class="input-group-addon">s</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($settingsForm->get('powercost')) ?>
                    <div class="input-group">
                        <?= $this->formElement($settingsForm->get('powercost')) ?>
                        <div class="input-group-addon">€</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>

<!--Wallets-->
<div id="walletsPanel" class="panel panel-default">
    <div id="walletsPanelHeading" class="panel-heading">
        <strong>Wallets</strong>
        <div class="pull-right">
            <button class="btn btn-success btn-xs" id="addWallet" data-toggle="modal" data-target="#addUpdWalletModal">Add</button>
        </div>
    </div>
    <div id="walletsPanelBody" class="panel-body text-center">
        <div class="table-responsive">
            <table id="walletsTable" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                <thead>
                <th>ID</th>
                <th>Type</th>
                <th>Wallet ID</th>
                <th>Balance</th>
                <th>Edit</th>
                <th>Delete</th>
                </thead>
            </table>
        </div> 
    </div>
</div>

<!--Wemo-->
<div id="wemosPanel" class="panel panel-default">
    <div id="wemosPanelHeading" class="panel-heading">
        <strong>Wemo</strong>
        <div class="pull-right">
            <button class="btn btn-success btn-xs" id="addWemo" data-toggle="modal" data-target="#addUpdWemoModal">Add</button>
        </div>
    </div>
    <div id="wemosPanelBody" class="panel-body text-center">
        <table id="wemosTable" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Type</th>
            <th>Edit</th>
            <th>Delete</th>
            </thead>
        </table>
    </div>
</div>

<!--Worker-->
<div id="workersPanel" class="panel panel-default">
    <div id="workersPanelHeading" class="panel-heading">
        <strong>Workers</strong>
        <div class="pull-right">
            <button class="btn btn-success btn-xs" id="addWorker" data-toggle="modal" data-target="#addUpdWorkerModal">Add</button>
        </div>
    </div>
    <div id="workersPanelBody" class="panel-body text-center">
        <table id="workersTable" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Ip</th>
            <th>Pool</th>
            <th>Wemo</th>
            <th>Software</th>
            <th>Software port</th>
            <th>Amp</th>
            <th>Wallet ID</th>
            <th>Ssh user</th>
            <th>Ssh password</th>
            <th>Ssh port</th>
            <th>Edit</th>
            <th>Delete</th>
            </thead>
        </table>
    </div>
</div>

<!-- Modal for adding and updating wallets -->
<div class="modal fade" id="addUpdWalletModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form id="addUpdWalletForm" method="POST" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 id="titleWalletModal">Add new wallet</h4>
                </div>

                <div class="modal-body">
                    <div id="statusWalletsMsg"></div>

                    <div class="form-group">
                        <label for="type">Type</label>
                        <select class="form-control" id="type">
                            <option value="null">---</option>
                            <option value="monero">Monero</option>
                            <option value="ethereum">Ethereum</option>
                            <option value="zcash">Zcash</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="number">Wallet ID</label>
                        <input type="text" id="number" placeholder="" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="balance">Balance</label>
                        <input type="text" id="balance" placeholder="0.0" class="form-control">
                    </div>

                </div>

                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" id="addUpdWalletBtn" value="Add wallet">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>

            </div>
        </form>
    </div>
</div>

<!-- Modal for deleting wallet -->
<div class="modal fade" id="deleteWalletModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4>You are deleting wallet ID: #<span id="walletIdSpan"></span></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deleteWalletBtn">Delete</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>		
        </div>
    </div>
</div>

<!-- Modal for adding and updating workers -->
<div class="modal fade" id="addUpdWorkerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form id="addUpdWorkerForm" method="POST" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 id="titleWorkerModal">Add new worker</h4>
                </div>

                <div class="modal-body">
                    <div id="statusWorkersMsg"></div>

                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" placeholder="" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="ip">Ip</label>
                        <input type="text" id="ip" placeholder="" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="pool">Pool</label>
                        <input type="text" id="pool" placeholder="" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="insight">Wemo</label>
                        <option value="null">---</option>
                        <select class="form-control" id="insight">
                            <?php
                            foreach ($wemosData as $wemo) {
                                echo '<option value="' . $wemo['id'] . '">' . $wemo['name'] . '</option>';
                            }
                            ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="software">Software</label>
                        <select class="form-control" id="software">
                            <option value="null">---</option>
                            <option value="xmr-stak">Xmr-stak</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="softwareport">Software port</label>
                        <input type="text" id="softwareport" placeholder="" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="amp">Amp</label>
                        <input type="text" id="amp" placeholder="" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="walletid">Wallet ID</label>
                        <option value="null">---</option>
                        <select class="form-control" id="walletid">
                            <?php
                            foreach ($walletsData as $wallet) {
                                $number = (strlen($wallet['number']) > 43) ? substr($wallet['number'], 0, 40) . '...' : $wallet['number'];
                                echo '<option value="' . $wallet['id'] . '">' . $wallet['type'] . ' : ' . $number . '</option>';
                            }
                            ?>
                        </select>
                    </div>
                    
                    <div class="form-group">
                        <label for="sshuser">Ssh user</label>
                        <input type="text" id="sshuser" placeholder="" class="form-control">
                    </div>
                    
                    <div class="form-group">
                        <label for="sshpassword">Ssh password</label>
                        <input type="text" id="sshpassword" placeholder="" class="form-control">
                    </div>
                    
                    <div class="form-group">
                        <label for="sshport">Ssh port</label>
                        <input type="text" id="sshport" placeholder="" class="form-control">
                    </div>

                </div>

                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" id="addUpdWorkerBtn" value="Add worker">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>

            </div>
        </form>
    </div>
</div>

<!-- Modal for deleting worker -->
<div class="modal fade" id="deleteWorkerModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4>You are deleting worker ID: #<span id="workerIdSpan"></span></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deleteWorkerBtn">Delete</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>		
        </div>
    </div>
</div>

<!-- Modal for adding and updating wemos -->
<div class="modal fade" id="addUpdWemoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form id="addUpdWemoForm" method="POST" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 id="titleWemoModal">Add new wemo</h4>
                </div>

                <div class="modal-body">
                    <div id="statusWemosMsg"></div>

                    <div class="form-group">
                        <label for="nameWemo">Name</label>
                        <input type="text" id="nameWemo" placeholder="" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="typeWemo">Type</label>
                        <select class="form-control" id="typeWemo">
                            <option value="switch">Switch</option>
                            <option value="insight">Insight</option>
                        </select>
                    </div>

                </div>

                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" id="addUpdWemoBtn" value="Add wemo">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>

            </div>
        </form>
    </div>
</div>

<!-- Modal for deleting wemo -->
<div class="modal fade" id="deleteWemoModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4>You are deleting wemo ID: #<span id="wemoIdSpan"></span></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deleteWemoBtn">Delete</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>		
        </div>
    </div>
</div>

<?php
$this->inlineScript()
        ->appendFile($this->basePath('js/ecmgui-settings.js'));
?>